{% set name = "whatthepatch" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5983a49f751158a7b5c62baf55aaf815728d3d80bf5dd0c5acb2d7d3d7391ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - whatthepatch
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cscorley/whatthepatch
  summary: What The Patch!? is a library for both parsing and applying patch files
  description: What The Patch!? is a library for both parsing and applying patch files
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/cscorley/whatthepatch
  dev_url: https://github.com/cscorley/whatthepatch

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - steff456
    - dalthviz
